language: go
go_import_path: github.com/SUSE/saptune
go:
  - 1.10.x
os:
  - linux
sudo: required

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - sudo -E env "PATH=$PATH" go test -v -coverprofile=c.out -cover ./...
  - go build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
