#!/usr/bin/env bash
# fake output of /usr/bin/systemd-detect-virt for unittests
# use-case - virtualization found

case "$1" in
"-r")
    echo ""
    ;;
"-c")
    echo "lxc"
    ;;
"-v")
    echo "kvm"
    ;;
*)
    echo "none"
    ;;
esac
exit 0
